// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Document struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	FolderID    pgtype.UUID
	AuthorID    pgtype.UUID
	Title       string
	Content     pgtype.Text
	IsPublic    bool
	Slug        string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	DeletedAt   pgtype.Timestamp
}

type Folder struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	Name        string
	ParentID    pgtype.UUID
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type Profile struct {
	ID        pgtype.UUID
	Username  string
	FullName  string
	AvatarUrl pgtype.Text
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}

type Workspace struct {
	ID        pgtype.UUID
	Name      string
	Slug      string
	CreatedBy pgtype.UUID
	CreatedAt pgtype.Timestamp
}

type WorkspaceMember struct {
	WorkspaceID pgtype.UUID
	UserID      pgtype.UUID
	Role        pgtype.Text
}
