// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addWorkspaceMember = `-- name: AddWorkspaceMember :exec
INSERT INTO workspace_members (workspace_id, user_id, role)
VALUES ($1, $2, $3)
`

type AddWorkspaceMemberParams struct {
	WorkspaceID pgtype.UUID
	UserID      pgtype.UUID
	Role        pgtype.Text
}

func (q *Queries) AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) error {
	_, err := q.db.Exec(ctx, addWorkspaceMember, arg.WorkspaceID, arg.UserID, arg.Role)
	return err
}

const checkFolderBelongsToWorkspace = `-- name: CheckFolderBelongsToWorkspace :one
SELECT id FROM folders 
WHERE id = $1 AND workspace_id = $2 LIMIT 1
`

type CheckFolderBelongsToWorkspaceParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

func (q *Queries) CheckFolderBelongsToWorkspace(ctx context.Context, arg CheckFolderBelongsToWorkspaceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, checkFolderBelongsToWorkspace, arg.ID, arg.WorkspaceID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const checkWorkspaceMember = `-- name: CheckWorkspaceMember :one
SELECT role FROM workspace_members
WHERE workspace_id = $1 AND user_id = $2 LIMIT 1
`

type CheckWorkspaceMemberParams struct {
	WorkspaceID pgtype.UUID
	UserID      pgtype.UUID
}

func (q *Queries) CheckWorkspaceMember(ctx context.Context, arg CheckWorkspaceMemberParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, checkWorkspaceMember, arg.WorkspaceID, arg.UserID)
	var role pgtype.Text
	err := row.Scan(&role)
	return role, err
}

const createDocument = `-- name: CreateDocument :one

INSERT INTO documents (workspace_id, folder_id, author_id, title, content, is_public)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workspace_id, folder_id, author_id, title, content, is_public, created_at, updated_at, deleted_at
`

type CreateDocumentParams struct {
	WorkspaceID pgtype.UUID
	FolderID    pgtype.UUID
	AuthorID    pgtype.UUID
	Title       string
	Content     pgtype.Text
	IsPublic    bool
}

// ==========================================
// DOMAIN DOKUMEN / CATATAN
// ==========================================
func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.WorkspaceID,
		arg.FolderID,
		arg.AuthorID,
		arg.Title,
		arg.Content,
		arg.IsPublic,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FolderID,
		&i.AuthorID,
		&i.Title,
		&i.Content,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createFolder = `-- name: CreateFolder :one

INSERT INTO folders (workspace_id, name, parent_id)
VALUES ($1, $2, $3)
RETURNING id, workspace_id, name, parent_id, created_at, updated_at
`

type CreateFolderParams struct {
	WorkspaceID pgtype.UUID
	Name        string
	ParentID    pgtype.UUID
}

// ==========================================
// DOMAIN KATEGORI / FOLDERS
// ==========================================
func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, createFolder, arg.WorkspaceID, arg.Name, arg.ParentID)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (id, username, full_name, avatar_url, updated_at)
VALUES ($1, $2, $3, $4, NOW())
RETURNING id, username, full_name, avatar_url, updated_at
`

type CreateProfileParams struct {
	ID        pgtype.UUID
	Username  string
	FullName  string
	AvatarUrl pgtype.Text
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, createProfile,
		arg.ID,
		arg.Username,
		arg.FullName,
		arg.AvatarUrl,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash)
VALUES ($1, $2)
RETURNING id, email, password_hash, created_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (id, name, slug, created_by, created_at)
VALUES (gen_random_uuid(), $1, $2, $3, NOW())
RETURNING id, name, slug, created_by, created_at
`

type CreateWorkspaceParams struct {
	Name      string
	Slug      string
	CreatedBy pgtype.UUID
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.Name, arg.Slug, arg.CreatedBy)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFolder = `-- name: DeleteFolder :execrows
DELETE FROM folders
WHERE id = $1 AND workspace_id = $2
`

type DeleteFolderParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

func (q *Queries) DeleteFolder(ctx context.Context, arg DeleteFolderParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFolder, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDocument = `-- name: GetDocument :one
SELECT id, workspace_id, folder_id, author_id, title, content, is_public, created_at, updated_at, deleted_at FROM documents 
WHERE id = $1 AND workspace_id = $2 LIMIT 1
`

type GetDocumentParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument, arg.ID, arg.WorkspaceID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FolderID,
		&i.AuthorID,
		&i.Title,
		&i.Content,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProfileByID = `-- name: GetProfileByID :one
SELECT id, username, full_name, avatar_url, updated_at FROM profiles
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProfileByID(ctx context.Context, id pgtype.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByID, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.UpdatedAt,
	)
	return i, err
}

const getTrashedDocuments = `-- name: GetTrashedDocuments :many

SELECT id, workspace_id, folder_id, author_id, title, content, is_public, created_at, updated_at, deleted_at FROM documents
WHERE workspace_id = $1 AND deleted_at IS NOT NULL
ORDER BY deleted_at DESC
`

// ==========================================
// RECYCLE BIN & HARD DELETE
// ==========================================
func (q *Queries) GetTrashedDocuments(ctx context.Context, workspaceID pgtype.UUID) ([]Document, error) {
	rows, err := q.db.Query(ctx, getTrashedDocuments, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.FolderID,
			&i.AuthorID,
			&i.Title,
			&i.Content,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, created_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserWorkspaces = `-- name: GetUserWorkspaces :many
SELECT w.id, w.name, w.slug, wm.role 
FROM workspaces w
JOIN workspace_members wm ON w.id = wm.workspace_id
WHERE wm.user_id = $1
`

type GetUserWorkspacesRow struct {
	ID   pgtype.UUID
	Name string
	Slug string
	Role pgtype.Text
}

func (q *Queries) GetUserWorkspaces(ctx context.Context, userID pgtype.UUID) ([]GetUserWorkspacesRow, error) {
	rows, err := q.db.Query(ctx, getUserWorkspaces, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserWorkspacesRow
	for rows.Next() {
		var i GetUserWorkspacesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceDocuments = `-- name: GetWorkspaceDocuments :many
SELECT id, workspace_id, folder_id, author_id, title, content, is_public, created_at, updated_at, deleted_at FROM documents
WHERE workspace_id = $1 AND deleted_at IS NULL
ORDER BY updated_at DESC
`

func (q *Queries) GetWorkspaceDocuments(ctx context.Context, workspaceID pgtype.UUID) ([]Document, error) {
	rows, err := q.db.Query(ctx, getWorkspaceDocuments, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.FolderID,
			&i.AuthorID,
			&i.Title,
			&i.Content,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceFolders = `-- name: GetWorkspaceFolders :many
SELECT id, workspace_id, name, parent_id, created_at, updated_at FROM folders
WHERE workspace_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetWorkspaceFolders(ctx context.Context, workspaceID pgtype.UUID) ([]Folder, error) {
	rows, err := q.db.Query(ctx, getWorkspaceFolders, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hardDeleteDocument = `-- name: HardDeleteDocument :execrows
DELETE FROM documents
WHERE id = $1 AND workspace_id = $2
`

type HardDeleteDocumentParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

func (q *Queries) HardDeleteDocument(ctx context.Context, arg HardDeleteDocumentParams) (int64, error) {
	result, err := q.db.Exec(ctx, hardDeleteDocument, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreDocument = `-- name: RestoreDocument :execrows

UPDATE documents
SET deleted_at = NULL, updated_at = NOW()
WHERE id = $1 AND workspace_id = $2
`

type RestoreDocumentParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

// Ganti query Hapus, Restore, dan Update lu menjadi seperti ini:
func (q *Queries) RestoreDocument(ctx context.Context, arg RestoreDocumentParams) (int64, error) {
	result, err := q.db.Exec(ctx, restoreDocument, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteDocument = `-- name: SoftDeleteDocument :execrows
UPDATE documents
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND workspace_id = $2
`

type SoftDeleteDocumentParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

func (q *Queries) SoftDeleteDocument(ctx context.Context, arg SoftDeleteDocumentParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteDocument, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE documents
SET 
    title = $3,
    content = $4,
    folder_id = $5,
    is_public = $6,
    updated_at = NOW()
WHERE id = $1 AND workspace_id = $2
RETURNING id, workspace_id, folder_id, author_id, title, content, is_public, created_at, updated_at, deleted_at
`

type UpdateDocumentParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	Title       string
	Content     pgtype.Text
	FolderID    pgtype.UUID
	IsPublic    bool
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocument,
		arg.ID,
		arg.WorkspaceID,
		arg.Title,
		arg.Content,
		arg.FolderID,
		arg.IsPublic,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FolderID,
		&i.AuthorID,
		&i.Title,
		&i.Content,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
