// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addWorkspaceMember = `-- name: AddWorkspaceMember :exec
INSERT INTO workspace_members (workspace_id, user_id, role)
VALUES ($1, $2, $3)
`

type AddWorkspaceMemberParams struct {
	WorkspaceID pgtype.UUID
	UserID      pgtype.UUID
	Role        pgtype.Text
}

func (q *Queries) AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) error {
	_, err := q.db.Exec(ctx, addWorkspaceMember, arg.WorkspaceID, arg.UserID, arg.Role)
	return err
}

const checkDocumentInWorkspace = `-- name: CheckDocumentInWorkspace :one
SELECT id FROM documents
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
LIMIT 1
`

type CheckDocumentInWorkspaceParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

// T-105 (validasi setter): dokumen harus milik workspace yang sama & belum dihapus.
func (q *Queries) CheckDocumentInWorkspace(ctx context.Context, arg CheckDocumentInWorkspaceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, checkDocumentInWorkspace, arg.ID, arg.WorkspaceID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const checkFolderBelongsToWorkspace = `-- name: CheckFolderBelongsToWorkspace :one
SELECT id FROM folders 
WHERE id = $1 AND workspace_id = $2 LIMIT 1
`

type CheckFolderBelongsToWorkspaceParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

func (q *Queries) CheckFolderBelongsToWorkspace(ctx context.Context, arg CheckFolderBelongsToWorkspaceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, checkFolderBelongsToWorkspace, arg.ID, arg.WorkspaceID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const checkWorkspaceMember = `-- name: CheckWorkspaceMember :one
SELECT role FROM workspace_members
WHERE workspace_id = $1 AND user_id = $2 LIMIT 1
`

type CheckWorkspaceMemberParams struct {
	WorkspaceID pgtype.UUID
	UserID      pgtype.UUID
}

func (q *Queries) CheckWorkspaceMember(ctx context.Context, arg CheckWorkspaceMemberParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, checkWorkspaceMember, arg.WorkspaceID, arg.UserID)
	var role pgtype.Text
	err := row.Scan(&role)
	return role, err
}

const createDocument = `-- name: CreateDocument :one

INSERT INTO documents (workspace_id, folder_id, author_id, title, content, is_public, slug)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, workspace_id, folder_id, author_id, title, content, is_public, slug, version, search_vector, published_at, created_at, updated_at, deleted_at, locked_by
`

type CreateDocumentParams struct {
	WorkspaceID pgtype.UUID
	FolderID    pgtype.UUID
	AuthorID    pgtype.UUID
	Title       string
	Content     pgtype.Text
	IsPublic    bool
	Slug        string
}

// ==========================================
// DOMAIN DOKUMEN / CATATAN
// ==========================================
func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.WorkspaceID,
		arg.FolderID,
		arg.AuthorID,
		arg.Title,
		arg.Content,
		arg.IsPublic,
		arg.Slug,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FolderID,
		&i.AuthorID,
		&i.Title,
		&i.Content,
		&i.IsPublic,
		&i.Slug,
		&i.Version,
		&i.SearchVector,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LockedBy,
	)
	return i, err
}

const createFolder = `-- name: CreateFolder :one

INSERT INTO folders (workspace_id, name, parent_id)
VALUES ($1, $2, $3)
RETURNING id, workspace_id, name, parent_id, index_document_id, created_at, updated_at
`

type CreateFolderParams struct {
	WorkspaceID pgtype.UUID
	Name        string
	ParentID    pgtype.UUID
}

// ==========================================
// DOMAIN KATEGORI / FOLDERS
// ==========================================
func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, createFolder, arg.WorkspaceID, arg.Name, arg.ParentID)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ParentID,
		&i.IndexDocumentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (id, username, full_name, avatar_url, updated_at)
VALUES ($1, $2, $3, $4, NOW())
RETURNING id, username, full_name, avatar_url, updated_at
`

type CreateProfileParams struct {
	ID        pgtype.UUID
	Username  string
	FullName  string
	AvatarUrl pgtype.Text
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, createProfile,
		arg.ID,
		arg.Username,
		arg.FullName,
		arg.AvatarUrl,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash)
VALUES ($1, $2)
RETURNING id, email, password_hash, created_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (id, name, slug, created_by, created_at)
VALUES (gen_random_uuid(), $1, $2, $3, NOW())
RETURNING id, name, slug, created_by, created_at
`

type CreateWorkspaceParams struct {
	Name      string
	Slug      string
	CreatedBy pgtype.UUID
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.Name, arg.Slug, arg.CreatedBy)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFolder = `-- name: DeleteFolder :execrows
DELETE FROM folders
WHERE id = $1 AND workspace_id = $2
`

type DeleteFolderParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

func (q *Queries) DeleteFolder(ctx context.Context, arg DeleteFolderParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFolder, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const forceUnlockDocument = `-- name: ForceUnlockDocument :execrows
UPDATE documents
SET locked_by = NULL, updated_at = NOW()
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL AND locked_by IS NOT NULL
`

type ForceUnlockDocumentParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

// Lepas kunci paksa (oleh OWNER): set locked_by = NULL tanpa peduli siapa pengunci.
func (q *Queries) ForceUnlockDocument(ctx context.Context, arg ForceUnlockDocumentParams) (int64, error) {
	result, err := q.db.Exec(ctx, forceUnlockDocument, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDocument = `-- name: GetDocument :one
SELECT id, workspace_id, folder_id, author_id, title, content, is_public, slug, version, search_vector, published_at, created_at, updated_at, deleted_at, locked_by FROM documents 
WHERE id = $1 AND workspace_id = $2 LIMIT 1
`

type GetDocumentParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument, arg.ID, arg.WorkspaceID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FolderID,
		&i.AuthorID,
		&i.Title,
		&i.Content,
		&i.IsPublic,
		&i.Slug,
		&i.Version,
		&i.SearchVector,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LockedBy,
	)
	return i, err
}

const getDocumentBySlug = `-- name: GetDocumentBySlug :one
SELECT id FROM documents
WHERE workspace_id = $1 AND slug = $2 AND deleted_at IS NULL
LIMIT 1
`

type GetDocumentBySlugParams struct {
	WorkspaceID pgtype.UUID
	Slug        string
}

// Cek apakah slug sudah dipakai di workspace (untuk disambiguator slug).
func (q *Queries) GetDocumentBySlug(ctx context.Context, arg GetDocumentBySlugParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getDocumentBySlug, arg.WorkspaceID, arg.Slug)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getDocumentLock = `-- name: GetDocumentLock :one
SELECT id, locked_by FROM documents
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
LIMIT 1
`

type GetDocumentLockParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

type GetDocumentLockRow struct {
	ID       pgtype.UUID
	LockedBy pgtype.UUID
}

// Ambil status kunci dokumen.
func (q *Queries) GetDocumentLock(ctx context.Context, arg GetDocumentLockParams) (GetDocumentLockRow, error) {
	row := q.db.QueryRow(ctx, getDocumentLock, arg.ID, arg.WorkspaceID)
	var i GetDocumentLockRow
	err := row.Scan(&i.ID, &i.LockedBy)
	return i, err
}

const getFolderWithIndex = `-- name: GetFolderWithIndex :one
SELECT
    f.id, f.workspace_id, f.parent_id, f.name, f.index_document_id,
    f.created_at, f.updated_at,
    d.id AS index_doc_id,
    d.title AS index_doc_title,
    d.slug AS index_doc_slug,
    d.content AS index_doc_content,
    d.updated_at AS index_doc_updated_at
FROM folders f
LEFT JOIN documents d
    ON d.id = f.index_document_id
    AND d.deleted_at IS NULL
WHERE f.id = $1 AND f.workspace_id = $2
LIMIT 1
`

type GetFolderWithIndexParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

type GetFolderWithIndexRow struct {
	ID                pgtype.UUID
	WorkspaceID       pgtype.UUID
	ParentID          pgtype.UUID
	Name              string
	IndexDocumentID   pgtype.UUID
	CreatedAt         pgtype.Timestamp
	UpdatedAt         pgtype.Timestamp
	IndexDocID        pgtype.UUID
	IndexDocTitle     pgtype.Text
	IndexDocSlug      pgtype.Text
	IndexDocContent   pgtype.Text
	IndexDocUpdatedAt pgtype.Timestamp
}

// T-105: folder satuan + dokumen indeksnya (README/wiki folder).
// LEFT JOIN: folder tanpa index TETAP tampil (field index_* bernilai NULL).
// Index doc yang di-soft-delete dianggap tidak ada (tidak dikembalikan).
func (q *Queries) GetFolderWithIndex(ctx context.Context, arg GetFolderWithIndexParams) (GetFolderWithIndexRow, error) {
	row := q.db.QueryRow(ctx, getFolderWithIndex, arg.ID, arg.WorkspaceID)
	var i GetFolderWithIndexRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ParentID,
		&i.Name,
		&i.IndexDocumentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IndexDocID,
		&i.IndexDocTitle,
		&i.IndexDocSlug,
		&i.IndexDocContent,
		&i.IndexDocUpdatedAt,
	)
	return i, err
}

const getProfileByID = `-- name: GetProfileByID :one
SELECT id, username, full_name, avatar_url, updated_at FROM profiles
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProfileByID(ctx context.Context, id pgtype.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByID, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublicDocumentBySlug = `-- name: GetPublicDocumentBySlug :one

SELECT 
    d.id, d.title, d.content, d.slug, d.is_public,
    d.created_at, d.updated_at,
    p.username AS author_username, 
    p.full_name AS author_full_name,
    p.avatar_url AS author_avatar_url
FROM documents d
JOIN profiles p ON d.author_id = p.id
JOIN workspaces w ON d.workspace_id = w.id
WHERE w.slug = $1
  AND d.slug = $2
  AND d.is_public = true
  AND d.deleted_at IS NULL
LIMIT 1
`

type GetPublicDocumentBySlugParams struct {
	Slug   string
	Slug_2 string
}

type GetPublicDocumentBySlugRow struct {
	ID              pgtype.UUID
	Title           string
	Content         pgtype.Text
	Slug            string
	IsPublic        bool
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	AuthorUsername  string
	AuthorFullName  string
	AuthorAvatarUrl pgtype.Text
}

// ==========================================
// GERBANG PUBLIK (Public Share Read-Only)
// ==========================================
// Endpoint publik: Tanpa JWT, keamanan 100% di level SQL.
// JOIN ke workspaces untuk resolve workspace_slug dari URL.
// JOIN ke profiles untuk ambil data author (anti N+1 query).
func (q *Queries) GetPublicDocumentBySlug(ctx context.Context, arg GetPublicDocumentBySlugParams) (GetPublicDocumentBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPublicDocumentBySlug, arg.Slug, arg.Slug_2)
	var i GetPublicDocumentBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Slug,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorUsername,
		&i.AuthorFullName,
		&i.AuthorAvatarUrl,
	)
	return i, err
}

const getRelatedNotes = `-- name: GetRelatedNotes :many

WITH current_doc AS (
    SELECT d.id AS doc_id, d.content FROM documents d WHERE d.id = $1
),
extracted_links AS (
    SELECT DISTINCT unnest(regexp_matches(cd.content, '\[\[([^\]]+)\]\]', 'g')) AS slug
    FROM current_doc cd
),
doc_links AS (
    SELECT DISTINCT d2.id, d2.title, d2.slug, 1.0 AS weight
    FROM documents d2
    JOIN extracted_links el ON el.slug = d2.slug
    WHERE d2.workspace_id = $2
      AND d2.deleted_at IS NULL
      AND d2.id != $1
),
doc_siblings AS (
    SELECT d3.id, d3.title, d3.slug, 0.5 AS weight
    FROM documents d3
    WHERE d3.workspace_id = $2
      AND d3.deleted_at IS NULL
      AND d3.id != $1
      AND d3.folder_id IS NOT DISTINCT FROM $3
      AND d3.id NOT IN (SELECT id FROM doc_links)
),
doc_similar AS (
    SELECT d4.id, d4.title, d4.slug, GREATEST(similarity(d4.title, $4), 0.1) AS weight
    FROM documents d4
    WHERE d4.workspace_id = $2
      AND d4.deleted_at IS NULL
      AND d4.id != $1
      AND d4.id NOT IN (SELECT id FROM doc_links)
      AND d4.id NOT IN (SELECT id FROM doc_siblings)
      AND similarity(d4.title, $4) > 0.05
)
SELECT id, title, slug, weight FROM doc_links
UNION ALL
SELECT id, title, slug, weight FROM doc_siblings
UNION ALL
SELECT id, title, slug, weight FROM doc_similar
ORDER BY weight DESC
LIMIT 10
`

type GetRelatedNotesParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	FolderID    pgtype.UUID
	Similarity  string
}

type GetRelatedNotesRow struct {
	ID     pgtype.UUID
	Title  string
	Slug   string
	Weight float64
}

// ==========================================
// T-109: CATATAN TERKAIT (Related Notes)
// ==========================================
// Rekomendasi catatan terkait: explicit [[link]] > sibling folder > trigram judul.
// $1 = document_id, $2 = workspace_id, $3 = folder_id, $4 = title_for_similarity.
func (q *Queries) GetRelatedNotes(ctx context.Context, arg GetRelatedNotesParams) ([]GetRelatedNotesRow, error) {
	rows, err := q.db.Query(ctx, getRelatedNotes,
		arg.ID,
		arg.WorkspaceID,
		arg.FolderID,
		arg.Similarity,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRelatedNotesRow
	for rows.Next() {
		var i GetRelatedNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Weight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrashedDocuments = `-- name: GetTrashedDocuments :many

SELECT id, workspace_id, folder_id, author_id, title, content, is_public, slug, version, search_vector, published_at, created_at, updated_at, deleted_at, locked_by FROM documents
WHERE workspace_id = $1 AND deleted_at IS NOT NULL
ORDER BY deleted_at DESC
`

// ==========================================
// RECYCLE BIN & HARD DELETE
// ==========================================
func (q *Queries) GetTrashedDocuments(ctx context.Context, workspaceID pgtype.UUID) ([]Document, error) {
	rows, err := q.db.Query(ctx, getTrashedDocuments, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.FolderID,
			&i.AuthorID,
			&i.Title,
			&i.Content,
			&i.IsPublic,
			&i.Slug,
			&i.Version,
			&i.SearchVector,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.LockedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, created_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserWorkspaces = `-- name: GetUserWorkspaces :many
SELECT w.id, w.name, w.slug, wm.role 
FROM workspaces w
JOIN workspace_members wm ON w.id = wm.workspace_id
WHERE wm.user_id = $1
`

type GetUserWorkspacesRow struct {
	ID   pgtype.UUID
	Name string
	Slug string
	Role pgtype.Text
}

func (q *Queries) GetUserWorkspaces(ctx context.Context, userID pgtype.UUID) ([]GetUserWorkspacesRow, error) {
	rows, err := q.db.Query(ctx, getUserWorkspaces, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserWorkspacesRow
	for rows.Next() {
		var i GetUserWorkspacesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceDocuments = `-- name: GetWorkspaceDocuments :many
SELECT id, workspace_id, folder_id, author_id, title, content, is_public, slug, version, search_vector, published_at, created_at, updated_at, deleted_at, locked_by FROM documents
WHERE workspace_id = $1 AND deleted_at IS NULL
ORDER BY updated_at DESC
`

func (q *Queries) GetWorkspaceDocuments(ctx context.Context, workspaceID pgtype.UUID) ([]Document, error) {
	rows, err := q.db.Query(ctx, getWorkspaceDocuments, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.FolderID,
			&i.AuthorID,
			&i.Title,
			&i.Content,
			&i.IsPublic,
			&i.Slug,
			&i.Version,
			&i.SearchVector,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.LockedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceFolders = `-- name: GetWorkspaceFolders :many
SELECT id, workspace_id, name, parent_id, index_document_id, created_at, updated_at FROM folders
WHERE workspace_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetWorkspaceFolders(ctx context.Context, workspaceID pgtype.UUID) ([]Folder, error) {
	rows, err := q.db.Query(ctx, getWorkspaceFolders, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.ParentID,
			&i.IndexDocumentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hardDeleteDocument = `-- name: HardDeleteDocument :execrows
DELETE FROM documents
WHERE id = $1 AND workspace_id = $2
`

type HardDeleteDocumentParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

func (q *Queries) HardDeleteDocument(ctx context.Context, arg HardDeleteDocumentParams) (int64, error) {
	result, err := q.db.Exec(ctx, hardDeleteDocument, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lockDocument = `-- name: LockDocument :execrows

UPDATE documents
SET locked_by = $3, updated_at = NOW()
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL AND locked_by IS NULL
`

type LockDocumentParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	LockedBy    pgtype.UUID
}

// ==========================================
// T-107: KUNCI READ-ONLY PER DOKUMEN
// ==========================================
// Kunci dokumen: set locked_by = user_id. Hanya berhasil jika belum dikunci.
func (q *Queries) LockDocument(ctx context.Context, arg LockDocumentParams) (int64, error) {
	result, err := q.db.Exec(ctx, lockDocument, arg.ID, arg.WorkspaceID, arg.LockedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreDocument = `-- name: RestoreDocument :execrows

UPDATE documents
SET deleted_at = NULL, updated_at = NOW()
WHERE id = $1 AND workspace_id = $2
`

type RestoreDocumentParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

// Ganti query Hapus, Restore, dan Update lu menjadi seperti ini:
func (q *Queries) RestoreDocument(ctx context.Context, arg RestoreDocumentParams) (int64, error) {
	result, err := q.db.Exec(ctx, restoreDocument, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const searchDocuments = `-- name: SearchDocuments :many

SELECT
    d.id, d.title, d.slug, d.folder_id, d.is_public, d.published_at,
    d.updated_at,
    ts_rank(d.search_vector, to_tsquery('simple', $2)) AS rank,
    similarity(d.title, $2) AS title_sim
FROM documents d
WHERE d.workspace_id = $1
  AND d.deleted_at IS NULL
  AND (
      d.search_vector @@ to_tsquery('simple', $2)
      OR similarity(d.title, $2) > 0.1
  )
ORDER BY
    ts_rank(d.search_vector, to_tsquery('simple', $2)) * 2
    + similarity(d.title, $2) DESC
LIMIT 50
`

type SearchDocumentsParams struct {
	WorkspaceID pgtype.UUID
	ToTsquery   string
}

type SearchDocumentsRow struct {
	ID          pgtype.UUID
	Title       string
	Slug        string
	FolderID    pgtype.UUID
	IsPublic    bool
	PublishedAt pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamp
	Rank        float32
	TitleSim    float32
}

// ==========================================
// T-108: PENCARIAN PINTAR (Search)
// ==========================================
// Pencarian full-text: tsvector rank + pg_trgm similarity.
// Ranking: title bobot lebih tinggi dari content.
// Hanya dokumen aktif (deleted_at IS NULL) di workspace yang sama.
// Pengguna yang bukan OWNER hanya melihat dokumen yang bisa diakses via role.
func (q *Queries) SearchDocuments(ctx context.Context, arg SearchDocumentsParams) ([]SearchDocumentsRow, error) {
	rows, err := q.db.Query(ctx, searchDocuments, arg.WorkspaceID, arg.ToTsquery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchDocumentsRow
	for rows.Next() {
		var i SearchDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.FolderID,
			&i.IsPublic,
			&i.PublishedAt,
			&i.UpdatedAt,
			&i.Rank,
			&i.TitleSim,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFolderIndexDocument = `-- name: SetFolderIndexDocument :execrows
UPDATE folders
SET index_document_id = $3, updated_at = NOW()
WHERE id = $1 AND workspace_id = $2
`

type SetFolderIndexDocumentParams struct {
	ID              pgtype.UUID
	WorkspaceID     pgtype.UUID
	IndexDocumentID pgtype.UUID
}

// T-105: pasang/hapus dokumen indeks folder. $3 NULL (valid:false) = hapus index.
func (q *Queries) SetFolderIndexDocument(ctx context.Context, arg SetFolderIndexDocumentParams) (int64, error) {
	result, err := q.db.Exec(ctx, setFolderIndexDocument, arg.ID, arg.WorkspaceID, arg.IndexDocumentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteDocument = `-- name: SoftDeleteDocument :execrows
UPDATE documents
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND workspace_id = $2
`

type SoftDeleteDocumentParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

func (q *Queries) SoftDeleteDocument(ctx context.Context, arg SoftDeleteDocumentParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteDocument, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unlockDocument = `-- name: UnlockDocument :execrows
UPDATE documents
SET locked_by = NULL, updated_at = NOW()
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL AND locked_by = $3
`

type UnlockDocumentParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	LockedBy    pgtype.UUID
}

// Lepas kunci dokumen: set locked_by = NULL. Hanya berhasil jika dikunci oleh user yang sama.
func (q *Queries) UnlockDocument(ctx context.Context, arg UnlockDocumentParams) (int64, error) {
	result, err := q.db.Exec(ctx, unlockDocument, arg.ID, arg.WorkspaceID, arg.LockedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE documents
SET 
    title = $3,
    content = $4,
    folder_id = $5,
    is_public = $6,
    updated_at = NOW(),
    version = version + 1
WHERE id = $1 AND workspace_id = $2 AND version = $7
RETURNING id, workspace_id, folder_id, author_id, title, content, is_public, slug, version, search_vector, published_at, created_at, updated_at, deleted_at, locked_by
`

type UpdateDocumentParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	Title       string
	Content     pgtype.Text
	FolderID    pgtype.UUID
	IsPublic    bool
	Version     int32
}

// Optimistic locking (T-101): hanya update jika version cocok, lalu naikkan version.
// Slug TIDAK di-update di sini (slug immutable setelah dibuat).
func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocument,
		arg.ID,
		arg.WorkspaceID,
		arg.Title,
		arg.Content,
		arg.FolderID,
		arg.IsPublic,
		arg.Version,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FolderID,
		&i.AuthorID,
		&i.Title,
		&i.Content,
		&i.IsPublic,
		&i.Slug,
		&i.Version,
		&i.SearchVector,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LockedBy,
	)
	return i, err
}
